language: python
    python: 
      - "3.6"
    services:
      - postgresql
    env:
      -DJANGO=2.1.7 DB=postgresql
    install:
      - pip install -r requirements.txt
    before_script:
      - psql -e 'create database test;' -u root
    script:
      - python manage.py test