# Generated by Django 2.1.7 on 2019-04-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('shares_held', models.IntegerField(blank=True, null=True)),
                ('member_active', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=8)),
                ('membership_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('shares_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('employment', models.CharField(max_length=30)),
                ('phone_dialing_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=12)),
                ('marital_status', models.CharField(max_length=15)),
                ('spouse_full_name', models.CharField(blank=True, max_length=25, null=True)),
                ('id_number', models.CharField(max_length=30)),
                ('id_attachment_front', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id_attachment_back', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('present_village', models.CharField(max_length=20)),
                ('present_subcounty', models.CharField(max_length=20)),
                ('present_county', models.CharField(max_length=20)),
                ('present_division', models.CharField(max_length=20)),
                ('present_district', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('institution_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institution_group', to='institution.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('running_balance', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('interest_accrued', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('group_member_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account_owner', to='members.GroupMember')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('savings_account_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account_related', to='members.SavingsAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SharesAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('shares_owned', models.IntegerField(default=0)),
                ('account_balance', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('running_balance', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('interest_accrued', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('group_member_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_account_owner', to='members.GroupMember')),
            ],
        ),
        migrations.CreateModel(
            name='SharesPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=20)),
                ('shares_bought', models.IntegerField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('shares_account_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account_related', to='members.SharesAccount')),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='members.LoanGroup'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
