# Generated by Django 2.1.7 on 2019-04-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_withdrawn', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date_withdrawn', models.DateTimeField(auto_now_add=True)),
                ('savings_account_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account_withdrawal', to='members.SavingsAccount')),
            ],
        ),
    ]
