# Generated by Django 2.1.7 on 2019-03-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('other_names', models.CharField(max_length=35)),
                ('email_address', models.EmailField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('employment', models.CharField(max_length=30)),
                ('phone_dialing_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=12)),
                ('marital_status', models.CharField(max_length=15)),
                ('spouse_full_name', models.CharField(blank=True, max_length=25, null=True)),
                ('id_number', models.CharField(max_length=30)),
                ('id_attachment_front', models.ImageField(upload_to='images')),
                ('id_attachment_back', models.ImageField(upload_to='images')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('present_village', models.CharField(max_length=20)),
                ('present_subcounty', models.CharField(max_length=20)),
                ('present_county', models.CharField(max_length=20)),
                ('present_division', models.CharField(max_length=20)),
                ('present_district', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='members.LoanGroup')),
            ],
        ),
    ]
