# Generated by Django 2.1.7 on 2019-03-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_groupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='member_id',
        ),
    ]
