# Generated by Django 2.1.7 on 2019-03-20 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_groupmember_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
