# Generated by Django 2.1.7 on 2019-03-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190320_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='other_names',
        ),
    ]
