# Generated by Django 2.1.7 on 2019-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20190321_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='id_attachment_back',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id_attachment_front',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
