# Generated by Django 2.1.7 on 2019-03-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20190321_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='username',
        ),
    ]
