# Generated by Django 2.1.7 on 2019-04-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20190418_1809'),
        ('members', '0008_remove_groupmember_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('interest_accrued', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharesAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('interest_accrued', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loangroup',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='member_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='shares_held',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loangroup',
            name='institution_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institution_group', to='institution.Institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id_attachment_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id_attachment_front',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
