# Generated by Django 2.1.7 on 2019-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20190418_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='membership_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='shares_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
