# Generated by Django 2.1.7 on 2019-04-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20190418_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='group_member_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='savings_account_owner', to='members.GroupMember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharesaccount',
            name='group_member_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shares_account_owner', to='members.GroupMember'),
            preserve_default=False,
        ),
    ]
