# Generated by Django 2.1.7 on 2019-04-27 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_date', models.DateTimeField()),
                ('cycle_status', models.CharField(default='Unpaid', max_length=100)),
                ('amount_expected', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('loan_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDisbursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_disbursed', models.DateTimeField(auto_now_add=True)),
                ('disbursed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursal_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('transaction_status', models.BooleanField(default=False)),
                ('balance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('fined_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('comment', models.TextField()),
                ('date_paid', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmation_officer', to=settings.AUTH_USER_MODEL)),
                ('related_loan_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_management.LoanCycles')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('loan_type', models.CharField(max_length=25)),
                ('loan_disbursement_date', models.DateField(blank=True, null=True)),
                ('first_repayment_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('expected_income_corebznss', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(^[0-9+-]+$)')])),
                ('expected_profit_corebznss', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(^[0-9+-]+$)')])),
                ('corebznss_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_cycle_frequency', models.CharField(max_length=10)),
                ('expected_duration', models.CharField(max_length=6)),
                ('loan_insurance_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('loan_processing_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('loan_balance_to_pay', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('loan_purpose', models.CharField(max_length=25)),
                ('loan_cycle', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_completed', models.BooleanField(default=False)),
                ('loan_status', models.BooleanField(default=False)),
                ('is_loan_disbursed', models.BooleanField(default=False)),
                ('loan_completed_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('guarantor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor_1', to='members.GroupMember')),
                ('guarantor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor_2', to='members.GroupMember')),
                ('loan_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='members.GroupMember')),
                ('responsible_loan_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loandisbursal',
            name='disbursed_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursed', to='loans_management.Loans'),
        ),
        migrations.AddField(
            model_name='loancycles',
            name='related_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_for_cycle', to='loans_management.Loans'),
        ),
        migrations.AddField(
            model_name='loanapproval',
            name='approved_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_approved', to='loans_management.Loans'),
        ),
    ]
