# Generated by Django 2.1.7 on 2019-03-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='expected_duration',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_insurance_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
