# Generated by Django 2.1.7 on 2019-03-24 04:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans_management', '0002_auto_20190324_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_date', models.DateTimeField()),
                ('cycle_status', models.CharField(default='Pending', max_length=100)),
                ('amount_expected', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(^[0-9+-]+$)')])),
                ('amount_paid', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('(^[0-9+-]+$)')])),
                ('balance', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('(^[0-9+-]+$)')])),
                ('loan_balance', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('(^[0-9+-]+$)')])),
            ],
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loancycles',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_management.Loans'),
        ),
    ]
