# Generated by Django 2.1.7 on 2019-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0004_auto_20190325_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancycles',
            name='amount_expected',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loancycles',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loancycles',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loancycles',
            name='loan_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
