# Generated by Django 2.1.7 on 2019-03-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0006_loanpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loancycles',
            old_name='loan',
            new_name='related_loan',
        ),
    ]
