# Generated by Django 2.1.7 on 2019-03-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0007_auto_20190326_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancycles',
            name='related_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_for_cycle', to='loans_management.Loans'),
        ),
    ]
