# Generated by Django 2.1.7 on 2019-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0008_auto_20190326_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancycles',
            name='cycle_status',
            field=models.CharField(default='Unpaid', max_length=100),
        ),
    ]
