# Generated by Django 2.1.7 on 2019-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0009_auto_20190326_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayments',
            name='date_paid',
            field=models.DateField(),
        ),
    ]
