# Generated by Django 2.1.7 on 2019-03-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0010_auto_20190326_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayments',
            name='transaction_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
