# Generated by Django 2.1.7 on 2019-03-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_management', '0011_loanpayments_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayments',
            name='transaction_status',
            field=models.BooleanField(default=False),
        ),
    ]
