# Generated by Django 2.1.7 on 2019-04-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=250)),
                ('institution_type', models.CharField(choices=[('MFI', 'MFI'), ('SACCO', 'SACCO')], max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('certificate_of_incoporation', models.ImageField(blank=True, null=True, upload_to='institutions/')),
                ('date_of_incoporation', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('membership_fee_frequency', models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('BI-MONTHLY', 'BI-MONTHLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BI-ANNUALLY', 'BI-ANNUALLY'), ('YEARLY', 'YEARLY')], max_length=20, null=True)),
                ('share_price', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('minimum_shares', models.IntegerField()),
                ('maximum_shares', models.IntegerField()),
                ('savings_amount', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('savings_frequency', models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('BI-MONTHLY', 'BI-MONTHLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BI-ANNUALLY', 'BI-ANNUALLY'), ('YEARLY', 'YEARLY')], max_length=20, null=True)),
                ('savings_interest', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('savings_interest_calculator', models.CharField(blank=True, choices=[('INCREASING_BALANCE', 'INCREASING_BALANCE'), ('SIMPLE_INTEREST', 'SIMPLE_INTEREST')], max_length=20, null=True)),
                ('savings_interest_frequency', models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('BI-MONTHLY', 'BI-MONTHLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BI-ANNUALLY', 'BI-ANNUALLY'), ('YEARLY', 'YEARLY')], max_length=20, null=True)),
                ('maximum_savings_to_withdraw', models.DecimalField(decimal_places=3, default=100, max_digits=20)),
                ('maximum_monthly_withdraws', models.IntegerField(default=0)),
                ('loan_types_provided', models.CharField(blank=True, choices=[('SMALL_LOAN', 'SMALL_LOAN'), ('BIG_LOAN', 'BIG_LOAN'), ('QUICK_LOAN', 'QUICK_LOAN')], max_length=15, null=True)),
                ('quick_loan_interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('small_loan_interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('big_loan_interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('quick_loan_limit', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('quick_loan_repayment_limit', models.IntegerField(default=0)),
                ('percentage_of_savings_rq_loan', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('loan_interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('small_loan_interest_calculator', models.CharField(blank=True, choices=[('REDUCING_BALANCE', 'REDUCING_BALANCE'), ('LEDGER_SYSTEM', 'LEDGER_SYSTEM'), ('SIMPLE_INTEREST', 'SIMPLE_INTEREST')], max_length=20, null=True)),
                ('quick_loan_interest_calculator', models.CharField(blank=True, choices=[('REDUCING_BALANCE', 'REDUCING_BALANCE'), ('LEDGER_SYSTEM', 'LEDGER_SYSTEM'), ('SIMPLE_INTEREST', 'SIMPLE_INTEREST')], max_length=20, null=True)),
                ('big_loan_interest_calculator', models.CharField(blank=True, choices=[('REDUCING_BALANCE', 'REDUCING_BALANCE'), ('LEDGER_SYSTEM', 'LEDGER_SYSTEM'), ('SIMPLE_INTEREST', 'SIMPLE_INTEREST')], max_length=20, null=True)),
                ('loan_guarantors_required', models.IntegerField()),
                ('loan_processing_fee_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('loan_insurance_fee_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('institution_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_related', to='institution.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=25)),
                ('staff_role', models.CharField(blank=True, choices=[('LOAN_OFFICER', 'LOAN_OFFICER'), ('MANAGER', 'MANAGER'), ('SECRETARY', 'SECRETARY')], max_length=20, null=True)),
                ('staff_responsibility', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_staff', to='institution.Institution')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
