# Generated by Django 2.1.7 on 2019-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institutiontransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='date_created',
        ),
        migrations.AddField(
            model_name='institution',
            name='is_institution_active',
            field=models.BooleanField(default=False),
        ),
    ]
