# Generated by Django 2.1.7 on 2019-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('MFI', 'MFI'), ('SACCO', 'SACCO')], max_length=25),
        ),
    ]
