# Generated by Django 2.1.7 on 2019-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20190418_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='certificate_of_incoporation',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='membership_fee_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('BI-MONTHLY', 'BI-MONTHLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BI-ANNUALLY', 'BI-ANNUALLY'), ('YEARLY', 'YEARLY')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='savings_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('BI-MONTHLY', 'BI-MONTHLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BI-ANNUALLY', 'BI-ANNUALLY'), ('YEARLY', 'YEARLY')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='savings_interest_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('BI-MONTHLY', 'BI-MONTHLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('BI-ANNUALLY', 'BI-ANNUALLY'), ('YEARLY', 'YEARLY')], max_length=20, null=True),
        ),
    ]
