# Generated by Django 2.1.7 on 2019-04-28 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institution_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
