# Generated by Django 2.1.7 on 2019-04-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20190418_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsettings',
            name='institution_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_related', to='institution.Institution'),
        ),
    ]
