# Generated by Django 2.1.7 on 2019-04-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20190428_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionstaff',
            name='staff_name',
        ),
    ]
