# Generated by Django 2.1.7 on 2019-04-30 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20190430_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionstaff',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
