FREQUENCY=(
    ("DAILY", "DAILY"),
    ("WEEKLY", "WEEKLY"),
    ("BI-MONTHLY", "BI-MONTHLY"),
    ("MONTHLY", "MONTHLY"),
    ("QUARTERLY", "QUARTERLY"),
    ("BI-ANNUALLY", "BI-ANNUALLY"),
    ("YEARLY", "YEARLY"),
)

ROLES=(
    ("LOAN_OFFICER", "LOAN_OFFICER"),
    ("BRANCH_MANAGER","BRANCH_MANAGER"),
    ("LOAN_MANAGER","LOAN_MANAGER"),
    ("TELLER","TELLER"),
    ("ASST_BRANCH_MANAGER","ASST_BRANCH_MANAGER"),
)

LOAN_TYPES=(
    ("SMALL_LOAN", "SMALL_LOAN"),
    ("BIG_LOAN", "BIG_LOAN"),
    ("QUICK_LOAN", "QUICK_LOAN"),
)

INTEREST_CALCULATORS=(
    ("INCREASING_BALANCE", "INCREASING_BALANCE"),
    ("SIMPLE_INTEREST","SIMPLE_INTEREST"),
)

LOAN_CALCULATORS=(
    ("REDUCING_BALANCE","REDUCING_BALANCE"),
    ("LEDGER_SYSTEM","LEDGER_SYSTEM"),
    ("SIMPLE_INTEREST","SIMPLE_INTEREST"),
)

INSTITUTION_TYPE=(
    ("MFI","MFI"),
    ("SACCO","SACCO"),
)